#define FONT_SIZE 9
#define TERM_WIDTH 250
#define TERM_HEIGHT 70
#define X_SCALE 2
#define INGAME_TERM_SIZE 20
#define GAME_WIDTH ((TERM_WIDTH - INGAME_TERM_SIZE) / X_SCALE)
#define GAME_HEIGHT TERM_HEIGHT
#define MAP_WIDTH (2*GAME_WIDTH)
#define MAP_HEIGHT (2*GAME_HEIGHT)
