#define TERM_WIDTH 360
#define TERM_HEIGHT 100
#define X_SCALE 2
#define INGAME_TERM_SIZE 20
#define GAME_WIDTH ((TERM_WIDTH - INGAME_TERM_SIZE) / X_SCALE)
#define GAME_HEIGHT TERM_HEIGHT
#define MAP_WIDTH (4*GAME_WIDTH)
#define MAP_HEIGHT (4*GAME_HEIGHT)
